#!/bin/bash
# gen-demo-data.sh — Génère brain-ui/src/data/demo.ts depuis les sources réelles
# Exécuter après chaque ajout/retrait d'agent, script ou doc
#
# Usage : bash scripts/gen-demo-data.sh

set -euo pipefail

BRAIN_ROOT="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
DEMO_FILE="$BRAIN_ROOT/brain-ui/src/data/demo.ts"
CATALOG="$BRAIN_ROOT/agents/CATALOG.yml"

# --- Comptages dynamiques ---

if command -v python3 &>/dev/null && python3 -c "import yaml" &>/dev/null 2>&1; then
  read -r TOTAL FREE PRO OWNER <<< "$(python3 - "$CATALOG" <<'PYEOF'
import yaml, sys
with open(sys.argv[1]) as f:
    agents = yaml.safe_load(f).get('agents', [])
tiers = {}
for a in agents:
    t = a.get('tier', 'free')
    tiers[t] = tiers.get(t, 0) + 1
free = tiers.get('free', 0) + tiers.get('featured', 0)
pro = tiers.get('pro', 0)
owner = tiers.get('full', 0) + tiers.get('owner', 0)
total = free + pro + owner
print(f"{total} {free} {pro} {owner}")
PYEOF
)"
else
  echo "⚠️  python3 + pyyaml requis pour lire CATALOG.yml" >&2
  exit 1
fi

SESSIONS=$(ls "$BRAIN_ROOT"/contexts/session-*.yml 2>/dev/null | wc -l)
SCRIPTS=$(ls "$BRAIN_ROOT"/scripts/*.sh "$BRAIN_ROOT"/scripts/*.py 2>/dev/null | wc -l)
DOCS=$(ls "$BRAIN_ROOT"/docs/*.md 2>/dev/null | wc -l)

# --- Générer docsList depuis les fichiers docs/ ---
DOCS_LIST=""
for f in "$BRAIN_ROOT"/docs/*.md; do
  [ -f "$f" ] || continue
  filename="$(basename "$f")"
  [ "$filename" = "README.md" ] && continue
  id="${filename%.md}"
  # Extraire le titre depuis le premier # du fichier
  title="$(head -5 "$f" | grep -m1 '^#' | sed 's/^#\+ //' | sed "s/'/\\\\'/g")"
  [ -z "$title" ] && title="$id"
  DOCS_LIST="${DOCS_LIST}    { id: '$id', title: '$title', file: '$filename' },
"
done

# --- Écrire demo.ts ---
cat > "$DEMO_FILE" <<TSEOF
// Auto-generated by scripts/gen-demo-data.sh — do not edit manually
// Run: bash scripts/gen-demo-data.sh

export const DEMO_DATA = {
  agents: {
    total: $TOTAL,
    free: $FREE,
    pro: $PRO,
    owner: $OWNER,
  },
  sessions: $SESSIONS,
  scripts: $SCRIPTS,
  docs: $DOCS,
  projects: [
    {
      name: 'my-saas-app',
      description: 'SaaS multi-tenant — exemple a remplacer',
      status: 'scaffold',
    },
    {
      name: 'my-game',
      description: 'Jeu indie — exemple a remplacer',
      status: 'scaffold',
    },
    {
      name: 'my-website',
      description: 'Portfolio / vitrine — exemple a remplacer',
      status: 'scaffold',
    },
  ],
  activity: [
    { action: 'Brain installe — template fork', time: 'Maintenant' },
    { action: 'PATHS.md configure', time: 'Au setup' },
    { action: 'Premier boot — session explore', time: 'A venir' },
    { action: 'Premier sprint — brain boot mode work/...', time: 'A venir' },
  ],
  cosmosNodes: [
    { id: 'kernel', label: 'KERNEL', x: 0, y: 0, z: 0, size: 2.5, color: '#f25c7a' },
    { id: 'agents', label: 'Agents', x: 3, y: 1, z: -1, size: 1.8, color: '#c9a0ff' },
    { id: 'sessions', label: 'Sessions', x: -2, y: 2, z: 1, size: 1.5, color: '#a4b4ff' },
    { id: 'projects', label: 'Projets', x: 1, y: -2, z: 2, size: 1.5, color: '#89dceb' },
    { id: 'scripts', label: 'Scripts', x: -3, y: -1, z: -2, size: 1.3, color: '#f25c7a' },
    { id: 'wiki', label: 'Wiki', x: 2, y: 3, z: 0, size: 1.2, color: '#e8c87a' },
    { id: 'docs', label: 'Docs', x: -1, y: -3, z: -1, size: 1.2, color: '#fb923c' },
    { id: 'brain-engine', label: 'Engine', x: 4, y: 0, z: 1, size: 1.4, color: '#9adba8' },
    { id: 'bsi', label: 'BSI', x: -2, y: 1, z: -3, size: 1.3, color: '#a4b4ff' },
    { id: 'tier', label: 'Tier Gate', x: 0, y: 3, z: 2, size: 1.1, color: '#ff4da6' },
  ],
  cosmosEdges: [
    { from: 'kernel', to: 'agents' },
    { from: 'kernel', to: 'sessions' },
    { from: 'kernel', to: 'scripts' },
    { from: 'kernel', to: 'tier' },
    { from: 'agents', to: 'sessions' },
    { from: 'agents', to: 'projects' },
    { from: 'sessions', to: 'bsi' },
    { from: 'projects', to: 'docs' },
    { from: 'scripts', to: 'brain-engine' },
    { from: 'brain-engine', to: 'bsi' },
    { from: 'wiki', to: 'docs' },
    { from: 'tier', to: 'agents' },
  ],
  docsList: [
${DOCS_LIST}  ],
}
TSEOF

echo "✅ demo.ts généré — agents: $TOTAL ($FREE free / $PRO pro / $OWNER owner) | sessions: $SESSIONS | scripts: $SCRIPTS | docs: $DOCS"
